# directives of the http context, shared by all server blocks

# reverse proxy cache
proxy_cache_path /var/cache/nginx/data-fair levels=1:2 keys_zone=data-fair-cache:10m inactive=10d max_size=10g;
# host based routing serves different content on the same path
proxy_cache_key $scheme$host$request_uri;

# format of the logs sent to the metrics daemon, use header origin if referer is empty
map $http_referer $reqref {
  default $http_referer;
  '' $http_origin;
}
log_format metrics escape=json '["$host","$reqref",$request_time,$bytes_sent,$status,"$upstream_http_x_owner","$cookie_id_token","$cookie_id_token_org","$http_x_apikey","$http_x_account","$http_x_processing","$upstream_cache_status","$upstream_http_x_resource","$upstream_http_x_operation","$gzip_ratio"]';
