# locations of the main domain, no path prefix is stripped
location = / { return 302 /data-fair/; }
location /data-fair/ { set $upstream http://data-fair:8080; proxy_pass $upstream; }
location /simple-directory/ { set $upstream http://simple-directory:8080; proxy_pass $upstream; }
location /events/ { set $upstream http://events:8080; proxy_pass $upstream; }
location /openapi-viewer/ { set $upstream http://openapi-viewer:8080; proxy_pass $upstream; }
location /capture/ { set $upstream http://capture:8080; proxy_pass $upstream; }
location /portals-manager/ { set $upstream http://portals-manager:8080; proxy_pass $upstream; }
location /metrics/ { set $upstream http://metrics:8080; proxy_pass $upstream; }
include /etc/nginx/includes/bonus-locations.conf;
